### ISSUE TITLE
[BUG] Crashed before the scrape

### ISSUE THREAD

**Issue by bewbylover** [Jules-WinnfieldX/CyberDropDownloader#739]
**Describe the bug**
Extension of https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/738 after updating to 5.1.9.

```
An error occurred, please report this to the developer
unhandled errors in a TaskGroup (1 sub-exception)
  + Exception Group Traceback (most recent call last):
  |   File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 85, in director
  |     await runtime(manager)
  |   File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 43, in runtime
  |     async with asyncio.TaskGroup() as task_group:
  |   File "/usr/lib/python3.11/asyncio/taskgroups.py", line 147, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/scraper/crawler.py", line 52, in run
    |     await self.fetch(item)
    |   File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/scraper/crawlers/gofile_crawler.py", line 37, in fetch
    |     await self.get_token(self.client)
    |   File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/utils/utilities.py", line 58, in wrapper
    |     link = args[0].url
    |            ^^^^^^^^^^^
    | AttributeError: 'ScraperClient' object has no attribute 'url'
    +------------------------------------

```

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Start program with a number of simp, nudo, xbunker, and social forum links.
2. Just wait.

**Screenshots**
![Screenshot from 2023-12-18 16-31-56](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/152096820/097c6d91-ecff-49fc-9d2c-cceeab9b8156)

**Setup Information**
 - OS: Ubuntu 20.04.6 LTS
 - python 3.11.6
 - Cyberdrop Downloader V5.1.9

**Downloader.log file**
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13709710/downloader.log)

**Additional context**

**Comment by Jules-WinnfieldX** [comment]
Try: 5.1.11

**Comment by bewbylover** [comment]
Downloads still have a strange display behavior.  Canceled mid processing through Ctrl+C.  Downloads is loading this status, but isn't clearing.  I'll restart and see if I can get a successful download and update.
[downloader.log](https://github.com/Jules-WinnfieldX/CyberDropDownloader/files/13709760/downloader.log)
![Screenshot from 2023-12-18 16-42-10](https://github.com/Jules-WinnfieldX/CyberDropDownloader/assets/152096820/dd9dc1ad-a4cd-4075-aeea-98cb3c80b76c)

**Comment by Jules-WinnfieldX** [comment]
Some sites don't send the content length in the headers, so they'll remain /0 bytes... Unless you are talking about a different behavior.

**Comment by bewbylover** [comment]
Right but they should clear.  What I think I am seeing is them being present and not clearing.  Very likely they are not downloading and are hung somehow.  I restarted and have 45.1K attempts with 0 successful downloads.  From the log one of the files is:

https://streamtape.com/v/2keWgZmvdPtP7v/Solomia_Maievska_lastest_onlyfans_12min_new_complete_video.mp4

Which loads fine for me in the browser, but is not downloading started at 2023-12-18 16:45:44,241 and no file in downloads and the time now is 2023-12-18 16:57:01,341

**Comment by Jules-WinnfieldX** [comment]
Anything that remains at 0/0 means it's not downloading, the first number is how much has downloaded. So even if the program doesn't receive that header info, that number should still increase if it is downloading. Though I doubt that file will download.

**Comment by Jules-WinnfieldX** [comment]
But it should error out

**Comment by bewbylover** [comment]
How long should it take to error?  That was about 12 minutes.

**Comment by Jules-WinnfieldX** [comment]
should be pretty instantaneous. I'll try and look into it later

**Comment by bewbylover** [comment]
No rush, just wanted you to know.  Thanks.

**Comment by bewbylover** [comment]
It is downloading things, but the error-ed out downloads aren't clearing so it is hard to know what is going on.  Updated to 5.1.12 and am still seeing the behavior.  I'll keep updating and checking as you push new releases.

**Comment by Jules-WinnfieldX** [comment]
5.1.13 going up now should fix this.
